##############################################################################
## Example: Configuraftion for running ecmc ruckig plugin
##############################################################################

## Initiation:
epicsEnvSet("IOC" ,"$(IOC="IOC_TEST")")
epicsEnvSet("ECMCCFG_INIT" ,"")  #Only run startup once (auto at PSI, need call at ESS), variable set to "#" in startup.cmd
epicsEnvSet("SCRIPTEXEC" ,"$(SCRIPTEXEC="iocshLoad")")

require ecmccfg 7.0.0

# run module startup.cmd (only needed at ESS  PSI auto call at require)
$(ECMCCFG_INIT)$(SCRIPTEXEC) ${ecmccfg_DIR}startup.cmd, "IOC=$(IOC),ECMC_VER=develop, MASTER_ID=-1"

##############################################################################
## Config hardware:
# No EtherCAT hardware..

##############################################################################
## PLC 1
#$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=1, SAMPLE_RATE_MS=1,FILE=./plc/el1252.plc, PLC_MACROS=',SLAVE_ID=${ECMC_EC_SLAVE_NUM}'")

########################################################################s######
require ecmc_plugin_ruckig master

## Load plugin: ruckig
epicsEnvSet(ECMC_PLUGIN_FILNAME,"$(ecmc_plugin_ruckig_DIR)lib/${EPICS_HOST_ARCH=linux-x86_64}/libecmc_plugin_ruckig.so")
epicsEnvSet(ECMC_PLUGIN_CONFIG,"DBG_PRINT=0;N")
${SCRIPTEXEC} ${ecmccfg_DIR}loadPlugin.cmd, "PLUGIN_ID=0,FILE=${ECMC_PLUGIN_FILNAME},CONFIG='${ECMC_PLUGIN_CONFIG}', REPORT=1"

##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"

##############################################################################
############# Go active:
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)

iocInit()

dbl > pvs.log
